spring:
  application:
    name: springboot-crud-web-app
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Add debug logging
logging:
  level:
    org.springdoc: INFO
    org.springframework.web: INFO
    root: INFO

# Springdoc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.webapp.springboot_crud_web_app

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "info"
  endpoint:
    health:
      show-details: always
    
# Profiles configuration
---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 